config/routes.rb
Alitech::Application.routes.draw do

  resources :seja_investidores
  resources :consultorias
  resources :outsourcings
  resources :celula_produtivas
  resources :vagas
  resources :ideia_prods
  resources :empresas
  resources :fale_conoscos
  resources :nossosparceiros 
  resources :produtos

  root :to => 'home#index'

end

app/models/fale_conosco.rb
class FaleConosco < ActiveRecord::Base
  attr_accessible :assunto, :cidade, :email, :empresa, :mensagem, :nome, :site, :telefone, :uf

  validates_presence_of :nome
  validates_presence_of :email
  validates_presence_of :assunto
  validates_presence_of :mensagem
  validates_presence_of :telefone

end

app/models/ideia_prod.rb
class IdeiaProd < ActiveRecord::Base
  attr_accessible :cidade, :descricao, :email, :nome, :telefone, :uf
end

app/models/seja_investidore.rb
class SejaInvestidore < ActiveRecord::Base
  attr_accessible :cidade, :email, :empresa, :mensagem, :nome, :site, :telefone, :uf
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/consultorias_controller.rb
class ConsultoriasController < ApplicationController
  def index
  end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController


  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @pagina_principal  = 'S'
  end
  
end

app/controllers/ideia_prods_controller.rb
class IdeiaProdsController < ApplicationController
  # GET /ideia_prods/new
  # GET /ideia_prods/new.json
  def new
    @ideia_prod = IdeiaProd.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ideia_prod }
    end
  end

  # POST /ideia_prods
  # POST /ideia_prods.json
  def create
    @ideia_prod = IdeiaProd.new(params[:ideia_prod])

    respond_to do |format|
      if @ideia_prod.save
        format.html { redirect_to @ideia_prod, notice: 'Ideia prod was successfully created.' }
        format.json { render json: @ideia_prod, status: :created, location: @ideia_prod }
      else
        format.html { render action: "new" }
        format.json { render json: @ideia_prod.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  def index
  end
end

app/controllers/seja_investidores_controller.rb
class SejaInvestidoresController < ApplicationController
  # GET /seja_investidores
  # GET /seja_investidores.json
  def index
    @seja_investidores = SejaInvestidore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @seja_investidores }
    end
  end

  # GET /seja_investidores/1
  # GET /seja_investidores/1.json
  def show
    @seja_investidore = SejaInvestidore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @seja_investidore }
    end
  end

  # GET /seja_investidores/new
  # GET /seja_investidores/new.json
  def new
    @seja_investidore = SejaInvestidore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @seja_investidore }
    end
  end

  # GET /seja_investidores/1/edit
  def edit
    @seja_investidore = SejaInvestidore.find(params[:id])
  end

  # POST /seja_investidores
  # POST /seja_investidores.json
  def create
    @seja_investidore = SejaInvestidore.new(params[:seja_investidore])

    respond_to do |format|
      if @seja_investidore.save
        format.html { redirect_to @seja_investidore, notice: 'Seja investidore was successfully created.' }
        format.json { render json: @seja_investidore, status: :created, location: @seja_investidore }
      else
        format.html { render action: "new" }
        format.json { render json: @seja_investidore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /seja_investidores/1
  # PUT /seja_investidores/1.json
  def update
    @seja_investidore = SejaInvestidore.find(params[:id])

    respond_to do |format|
      if @seja_investidore.update_attributes(params[:seja_investidore])
        format.html { redirect_to @seja_investidore, notice: 'Seja investidore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @seja_investidore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seja_investidores/1
  # DELETE /seja_investidores/1.json
  def destroy
    @seja_investidore = SejaInvestidore.find(params[:id])
    @seja_investidore.destroy

    respond_to do |format|
      format.html { redirect_to seja_investidores_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/vagas_controller.rb
class VagasController < ApplicationController
  
  def index
      @title = 'Vagas'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/celula_produtivas_helper.rb
module CelulaProdutivasHelper
end

app/helpers/consultorias_helper.rb
module ConsultoriasHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/fale_conoscos_helper.rb
module FaleConoscosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideia_prods_helper.rb
module IdeiaProdsHelper
end

app/helpers/nossosparceiros_helper.rb
module NossosparceirosHelper
end

app/helpers/outsourcings_helper.rb
module OutsourcingsHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/seja_investidores_helper.rb
module SejaInvestidoresHelper
end

app/helpers/vagas_helper.rb
module VagasHelper
end

app/views/seja_investidores/_form.html.erb
<%= form_for @seja_investidore do |f| %>
<% if @seja_investidore.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@seja_investidore.errors.count, "error") %> prohibited this seja_investidore from being saved:</h2>

	<ul>
		<% @seja_investidore.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="controls controls-row">
	<%= f.label :nome %>
	<%= f.label :empresa %>
	<%= f.text_field :nome %>
	<%= f.text_field :empresa %>
</div>
<div class="controls controls-row">
	<%= f.label :email %>
	<%= f.label :telefone %>
	<%= f.email_field :email %>
	<%= f.telephone_field :telefone %>
</div>
<div class="controls">
	<%= f.label :site %>
	<%= f.text_field :site %>
</div>
<div class="controls controls-row">
	<%= f.label :cidade %>
	<%= f.label :uf %>
	<%= f.text_field :cidade %>
	<%= f.text_field :uf %>
</div>
<div class="controls">
	<%= f.text_area :mensagem, :cols => "150", :rows => "5", :placeholder=>"Mensagem" %>
</div>
<div class="actions">
	<%= f.submit 'Enviar Mensagem',  :class=>"btn btn-primary" %>
</div>
<% end %>

app/views/seja_investidores/edit.html.erb
<h1>Editing seja_investidore</h1>

<%= render 'form' %>

<%= link_to 'Show', @seja_investidore %> |
<%= link_to 'Back', seja_investidores_path %>

app/views/seja_investidores/index.html.erb
<h1>Listing seja_investidores</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Email</th>
    <th>Telefone</th>
    <th>Empresa</th>
    <th>Site</th>
    <th>Cidade</th>
    <th>Uf</th>
    <th>Mensagem</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seja_investidores.each do |seja_investidore| %>
  <tr>
    <td><%= seja_investidore.nome %></td>
    <td><%= seja_investidore.email %></td>
    <td><%= seja_investidore.telefone %></td>
    <td><%= seja_investidore.empresa %></td>
    <td><%= seja_investidore.site %></td>
    <td><%= seja_investidore.cidade %></td>
    <td><%= seja_investidore.uf %></td>
    <td><%= seja_investidore.mensagem %></td>
    <td><%= link_to 'Show', seja_investidore %></td>
    <td><%= link_to 'Edit', edit_seja_investidore_path(seja_investidore) %></td>
    <td><%= link_to 'Destroy', seja_investidore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Seja investidore', new_seja_investidore_path %>

app/views/seja_investidores/new.html.erb
<%= render 'form' %>

app/views/seja_investidores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @seja_investidore.nome %>
</p>

<p>
  <b>Email:</b>
  <%= @seja_investidore.email %>
</p>

<p>
  <b>Telefone:</b>
  <%= @seja_investidore.telefone %>
</p>

<p>
  <b>Empresa:</b>
  <%= @seja_investidore.empresa %>
</p>

<p>
  <b>Site:</b>
  <%= @seja_investidore.site %>
</p>

<p>
  <b>Cidade:</b>
  <%= @seja_investidore.cidade %>
</p>

<p>
  <b>Uf:</b>
  <%= @seja_investidore.uf %>
</p>

<p>
  <b>Mensagem:</b>
  <%= @seja_investidore.mensagem %>
</p>


<%= link_to 'Edit', edit_seja_investidore_path(@seja_investidore) %> |
<%= link_to 'Back', seja_investidores_path %>